spring:
  application:
    name: 01-sb-restapi-graphql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productdb
    username: admin
    password: 12345

server:
  port: 9092